name: Build and Publish to Google Cloud

on:
  push:
    branches: [ "acceptance" ]
  pull_request:
    branches: [ "acceptance" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Build with Maven
        run: mvn clean package

      - name: Log recent commit
        run: git log -1

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Upload JAR to Google Cloud Storage'
        run: 'gcloud storage cp target/*.jar gs://jabberpoint_acceptance_bucket/testFolder'
