name: Java CI with Maven

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 19
      uses: actions/setup-java@v1
      with:
        java-version: '19'
#        distribution: 'oracle'
#        cache: maven
        
    - name: Build
      run: mvn --batch-mode -DskipTests package

    - name: Test
      run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

#    - name: Report
#      uses: dorny/test-reporter@v1
#      if: always()
#      with:
#        name: Maven Tests
#        path: target/surefire-reports/*.xml
#        reporter: java-junit
#        fail-on-error: true
    - name: Report
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Maven Tests
        path: target/surefire-reports/*.xml
